spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect